name: superstore_dbt
version: "1.0.0"

profile: superstore_dbt

model-paths: ["models"]
seed-paths: ["seeds"]
test-paths: ["tests"]
macro-paths: ["macros"]
target-path: "target"
clean-targets: ["target", "dbt_packages"]

models:
  superstore_dbt:
    staging:
      +materialized: view
    marts:
      +materialized: table
